Private Events web application with user authentication using Rails Associations
emasdev/private-events pull request #1
Opened 2020-08-28 21:58 UTC by emasdev

## About Private Events
- Users can create events and sign to attendee an event. Events take place at a specific date and at a location.

## Goal
- The main goal is to demonstrate mastering in building Rails Associations

## Features

If you're not an authenticated user

- Create User
- Log in

If you are an authenticated user

- See the list of Events available divided by upcoming and previous events
- See users attendance list
- See the attendance list for a specific event
- Register to attend an event

Rspec Testing available

2020-08-28 23:00 UTC, maelfosso requested changes
# Changes required :red_circle: 

Hello,
Thank you for the job done so far. However, there are some missing requirements

1. There is no link to see the user profile and the events is attended or will attend as requested [here](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_events_requirement.png)

2. There is no link for the event details. It's a [requirement](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/events_attendees_requirement.png)

3. Kindly add integration tests. It required. [Read it here](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_events_requirement.png)

5 Read the comments left below.

Kindly make the suggested changes  and submit a new code review request
Thanks

Mael FOSSO

2020-08-28 23:00 UTC, maelfosso commented on db/schema.rb
> +  end
Please, add index for the referential fields.

2020-08-28 23:00 UTC, maelfosso commented on app/views/layouts/application.html.erb
> +        <%end%>
Remove logic from views please. implement them in view helpers.

2020-08-28 23:00 UTC, maelfosso commented on app/controllers/events_controller.rb
> +    else
No needed. Add the new method into the `before_action` statement

2020-09-01 16:20 UTC, MarilenaRoque commented
Hello @maelfosso. Thanks for the review, the correction, and the clarifications about the requirements. :+1: 
We worked in all the topics listed and all the changes were implemented.

- [ ] Removed all the logic inside the view using helpers
- [ ] Added index for all the foreign keys
- [ ] Built integration tests

# :rocket:

2020-09-01 19:05 UTC, mosesogwo approved these changes
**Hello!:wave: Good job with the changes :+1:**

You can now merge this PR.

_**Cheers:stars:**_

### Status: Approved :heavy_check_mark:

2020-09-01 19:13 UTC, MarilenaRoque commented
# Thank you @mosesogwo! :rocket:

2020-09-01 19:14 UTC, merged